from typing import Any
import FreeCADGui

__url__: str

class Draft_SelectPlane:
    ac: str = ...
    param: Any = ...
    states: Any = ...
    def __init__(self) -> None: ...
    def GetResources(self): ...
    def IsActive(self): ...
    view: Any = ...
    wpButton: Any = ...
    taskd: Any = ...
    call: Any = ...
    def Activated(self) -> None: ...
    def finish(self, close: bool = ...): ...
    def reject(self): ...
    def action(self, arg: Any) -> None: ...
    def checkSelection(self) -> None: ...
    def handle(self): ...
    def setPlaneFromObjPlacement(self, obj: Any): ...
    def setPlaneOnWPProxy(self, obj: FreeCADGui.Object) -> None: ...
    def getCenterPoint(self, x: Any, y: Any, z: Any): ...
    def tostr(self, v: Any): ...
    def getOffset(self): ...
    def onClickTop(self) -> None: ...
    def onClickFront(self) -> None: ...
    def onClickSide(self) -> None: ...
    def onClickAlign(self) -> None: ...
    def onClickAuto(self) -> None: ...
    def onClickMove(self) -> None: ...
    def onClickCenter(self) -> None: ...
    def onClickPrevious(self) -> None: ...
    def onSetGridSize(self, text: Any) -> None: ...
    def onSetMainline(self, i: Any) -> None: ...
    def onSetSnapRadius(self, i: Any) -> None: ...
    def display(self, arg: Any): ...

def do_command_gui(lambda_or_function: Any) -> None: ...
